[profile.default]
src = "../l1-contracts/contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "contracts/=../l1-contracts/contracts/"
]
